### ISSUE TITLE
Set C++11 via -std=c++11 for gcc-5 in dcmtk-3.6.2?

### ISSUE THREAD

**Issue by holgersson32644** [gerddie/gentoo-imaging#11]
Hi, is it possible to build dcmtk with gcc-5 with CFLAGS="${CFLAGS} -std=c++11"? If so, the ebuild could be used with users of gentoo’s stable C++ compiler, too :-)
(I don’t have a gcc5 here, so I can’t test right now.)

**Comment by gerddie** [comment]
The ebuild already be used with g++-5, only enabling C++11 via the use flags doesn't work because then cmake doesn't run through because of some problem with  std::isnan.
On the other hand  for ginkgocadx C++11 via use flags is required with dcmtk-3.6.2, because if C++11 is not enabled  ginkgocadx chockes on the OFunique_ptr implementation provided by upstream.
That's why I tailored the ebuild as it is. 

I don't think, however, that setting c++11 via the CXXFLAGS gains you anything (it is possible though) but there is absolutely no problem to link a program compiled with c++11 against a library compiled without it. In fact until recently  did exactly that with DCMTK < 3.6.2 and ginkgocadx.

Hope that helps.

**Comment by holgersson32644** [comment]
Thanks for clarification!
